type TClassProps = {
    subject: string;
    description?: string;
    startDateTime: string;
    endDateTime: string;
    coach: string;
    recurring: boolean;
    meetingMode: "in-person" | "online";
    meetingType: "group" | "individual";
    invitedGuests: string[];
    location: string | null;
    wholeDay: boolean;
    color: string;
    eventActivity: string;
};

export const meetings: TClassProps[] = [
    {
        subject: "Weekly Scrabble Practice",
        description: "Join us for a fun Scrabble practice session.",
        startDateTime: "2024-10-01T09:00",
        endDateTime: "2024-10-01T11:00",
        recurring: true,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["alice@example.com", "bob@example.com"],
        location: "Room A",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "210, 70%, 60%",
        coach: "John Doe",
    },
    {
        subject: "Chess Tactics Workshop",
        description: "Learn advanced chess tactics.",
        startDateTime: "2024-10-03T14:00",
        endDateTime: "2024-10-03T16:00",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: [],
        location: "",
        wholeDay: false,
        eventActivity: "chess",
        color: "120, 60%, 50%",
        coach: "Jane Smith",
    },
    {
        subject: "Coding Bootcamp Session",
        description: "Interactive coding session for beginners.",
        startDateTime: "2024-10-05T10:00",
        endDateTime: "2024-10-05T12:00",
        recurring: true,
        meetingMode: "online",
        meetingType: "group",
        invitedGuests: ["carol@example.com"],
        location: "Zoom",
        wholeDay: false,
        eventActivity: "coding",
        color: "0, 80%, 60%",
        coach: "Alice Johnson",
    },
    {
        subject: "Scrabble Monthly Tournament",
        description: "Compete against other players in Scrabble.",
        startDateTime: "2024-10-07T13:00",
        endDateTime: "2024-10-07T17:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["dave@example.com", "eve@example.com"],
        location: "Community Center",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "30, 100%, 50%",
        coach: "Michael Brown",
    },
    {
        subject: "Chess Club Meeting",
        description: "Regular meeting for chess enthusiasts.",
        startDateTime: "2024-10-10T18:00",
        endDateTime: "2024-10-10T20:00",
        recurring: true,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["frank@example.com"],
        location: "Library",
        wholeDay: false,
        eventActivity: "chess",
        color: "30, 100%, 50%",
        coach: "Sarah Davis",
    },
    {
        subject: "Coding Challenge",
        description: "Participate in a fun coding challenge.",
        startDateTime: "2024-10-12T09:00",
        endDateTime: "2024-10-12T11:00",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["grace@example.com"],
        location: "Google Meet",
        wholeDay: false,
        eventActivity: "coding",
        color: "240, 100%, 50%",
        coach: "David Wilson",
    },
    {
        subject: "Scrabble Strategy Session",
        description: "Discuss strategies for improving Scrabble skills.",
        startDateTime: "2024-10-15T14:00",
        endDateTime: "2024-10-15T15:30",
        recurring: true,
        meetingMode: "online",
        meetingType: "group",
        invitedGuests: [],
        location: "Discord",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "180, 50%, 60%",
        coach: "Emily Clark",
    },
    {
        subject: "Chess Open Play",
        description: "Casual chess games with club members.",
        startDateTime: "2024-10-18T16:00",
        endDateTime: "2024-10-18T19:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["heidi@example.com"],
        location: "Game Room",
        wholeDay: false,
        eventActivity: "chess",
        color: "330, 70%, 60%",
        coach: "Robert Harris",
    },
    {
        subject: "Introduction to Coding",
        description: "An introductory session on basic coding principles.",
        startDateTime: "2024-10-20T11:00",
        endDateTime: "2024-10-20T12:30",
        recurring: true,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["ivan@example.com"],
        location: "",
        wholeDay: false,
        eventActivity: "coding",
        color: "180, 50%, 50%",
        coach: "Linda Martin",
    },
    {
        subject: "Knowing your two-letter words",
        description: "An introductory session on basic coding principles.",
        startDateTime: "2024-10-20T11:00",
        endDateTime: "2024-10-20T12:30",
        recurring: true,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["ivan@example.com"],
        location: "",
        wholeDay: false,
        eventActivity: "coding",
        color: "40, 60%, 50%",
        coach: "Linda Martin",
    },
    {
        subject: "Scrabble Weekend Get-Together",
        description: "A fun weekend gathering for Scrabble players.",
        startDateTime: "2024-10-21T10:00",
        endDateTime: "2024-10-21T13:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: [],
        location: "Cafe",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "240, 70%, 70%",
        coach: "James Wright",
    },
    {
        subject: "Chess Lecture Series",
        description: "Learn from expert chess players.",
        startDateTime: "2024-10-25T19:00",
        endDateTime: "2024-10-25T20:30",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["james@example.com"],
        location: "Webex",
        wholeDay: false,
        eventActivity: "chess",
        color: "300, 80%, 50%",
        coach: "Natalie Scott",
    },
    {
        subject: "Coding Bootcamp Review",
        description: "Review session for coding bootcamp participants.",
        startDateTime: "2024-10-28T10:00",
        endDateTime: "2024-10-28T12:00",
        recurring: true,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: [],
        location: "",
        wholeDay: false,
        eventActivity: "coding",
        color: "180, 50%, 40%",
        coach: "Kevin Young",
    },
    {
        subject: "Scrabble Challenge",
        description: "Challenge other players in Scrabble.",
        startDateTime: "2024-10-30T14:00",
        endDateTime: "2024-10-30T16:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["karen@example.com"],
        location: "Game Hall",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "0, 60%, 50%",
        coach: "Maria Turner",
    },
    {
        subject: "Chess Strategy Workshop",
        description: "Workshop focused on chess strategies.",
        startDateTime: "2024-11-01T15:00",
        endDateTime: "2024-11-01T17:00",
        recurring: true,
        meetingMode: "online",
        meetingType: "group",
        invitedGuests: [],
        location: "Zoom",
        wholeDay: false,
        eventActivity: "chess",
        color: "0, 60%, 50%",
        coach: "Daniel Lee",
    },
    {
        subject: "Coding Practices Session",
        description: "Session to practice coding skills.",
        startDateTime: "2024-11-03T09:00",
        endDateTime: "2024-11-03T11:00",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["lucas@example.com"],
        location: "Google Meet",
        wholeDay: false,
        eventActivity: "coding",
        color: "240, 90%, 60%",
        coach: "Sophia Brown",
    },
    {
        subject: "Scrabble Game Night",
        description: "Casual Scrabble games with friends.",
        startDateTime: "2024-11-05T19:00",
        endDateTime: "2024-11-05T22:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["mike@example.com"],
        location: "Friend's House",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "300, 100%, 70%",
        coach: "Tom Garcia",
    },
    {
        subject: "Chess Puzzle Night",
        description: "Solve chess puzzles with peers.",
        startDateTime: "2024-11-10T16:00",
        endDateTime: "2024-11-10T18:00",
        recurring: true,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: ["nora@example.com"],
        location: "Discord",
        wholeDay: false,
        eventActivity: "chess",
        color: "0, 40%, 50%",
        coach: "Kevin Martinez",
    },
    {
        subject: "Coding Review Session",
        description: "Review coding concepts learned in class.",
        startDateTime: "2024-11-12T11:00",
        endDateTime: "2024-11-12T12:30",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: [],
        location: "",
        wholeDay: false,
        eventActivity: "coding",
        color: "120, 100%, 60%",
        coach: "Liam Clark",
    },
    {
        subject: "Scrabble Workshop",
        description: "Workshop for Scrabble enthusiasts to enhance skills.",
        startDateTime: "2024-11-15T14:00",
        endDateTime: "2024-11-15T16:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["olivia@example.com"],
        location: "Local Cafe",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "60, 40%, 50%",
        coach: "Emma Williams",
    },
    {
        subject: "Chess Endgame Techniques",
        description: "Learn endgame techniques in chess.",
        startDateTime: "2024-11-20T13:00",
        endDateTime: "2024-11-20T15:00",
        recurring: false,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: [],
        location: "Zoom",
        wholeDay: false,
        eventActivity: "chess",
        color: "300, 60%, 40%",
        coach: "Oliver Davis",
    },
    {
        subject: "Advanced Coding Techniques",
        description: "Explore advanced coding techniques.",
        startDateTime: "2024-11-25T09:00",
        endDateTime: "2024-11-25T11:00",
        recurring: true,
        meetingMode: "online",
        meetingType: "individual",
        invitedGuests: [],
        location: "",
        wholeDay: false,
        eventActivity: "coding",
        color: "30, 60%, 50%",
        coach: "Mia Rodriguez",
    },
    {
        subject: "Scrabble Championships",
        description: "Compete in the annual Scrabble championships.",
        startDateTime: "2024-11-30T12:00",
        endDateTime: "2024-11-30T18:00",
        recurring: false,
        meetingMode: "in-person",
        meetingType: "group",
        invitedGuests: ["charles@example.com"],
        location: "Convention Center",
        wholeDay: false,
        eventActivity: "scrabble",
        color: "0, 100%, 50%",
        coach: "Sophia Lee",
    },
];
